#!/bin/sh

# Install system dependencies, not conda in this case
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib:$CONDA_PREFIX/hlhdf/lib:$CONDA_PREFIX/rave/lib

cp kernel.json /srv/conda/envs/notebook/share/jupyter/kernels/python3/
chown jovyan:jovyan /srv/conda/envs/notebook/share/jupyter/kernels/python3/kernel.json

